### ISSUE TITLE
We don't want "Scientific Data" branding

### ISSUE THREAD

**Issue by drj11** [hidelab/isa-explorer-demo#4]
Remove the Scientific Data logo. and replace it.

with what?

**Comment by winhide-shef** [comment]
Same as CAFcommons. Text

On 8 Mar 2018 at 06:31, David Jones <notifications@github.com> wrote:


Remove the Scientific Data logo. and replace it.

with what?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hidelab/isa-explorer-demo/issues/4>, or mute the thread

**Comment by drj11** [comment]
I created a new SVG logo file that removes the branding, https://github.com/hidelab/isa-explorer-demo/blob/master/unbrand-logo.svg

![screenie](https://user-images.githubusercontent.com/1215412/37206355-408b3bf6-2390-11e8-92b2-591076ef9e8b.png)
